import deck_of_cards as doc


my_deck = doc.Deck()
my_deck.shuffle()
print(my_deck.deal_card())
print(my_deck.deal_hand(5))
print(my_deck.deal_hand(5))
print(my_deck.deal_hand(5))
print(my_deck.deal_hand(5))
print(my_deck.deal_hand(5))
print(my_deck.deal_hand(5))
print(my_deck.deal_hand(5))
print(my_deck.deal_hand(5))
print(my_deck.deal_hand(5))
print(my_deck.deal_hand(5))
print(my_deck.deal_hand(5))
print(my_deck.deal_hand(3))
print(my_deck.count())
print(my_deck)
